default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maxim_photo
  #username: maxim_photo
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: maxim_photo_test

production:
  <<: *default
  database: maxim_photo
  username: maxim
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
